### ISSUE TITLE
Move crate to image-rs organization

### ISSUE THREAD

**Issue by pizzaiter** [image-rs/color_quant#7]
This crate is a dependency of the `gif` crate and seems to have been forgotten in the move of all `image`-related crates to the image-rs organization. See https://github.com/image-rs/image/issues/881. It would be a good idea to also move this repository as well as the crates.io ownership to the image-rs organization.

cc @bvssvni @HeroicKatora @fintelia

**Comment by bvssvni** [comment]
@nwin I agree with moving this library to the image-rs organization. What do you think?

**Comment by HeroicKatora** [comment]
I'm for it as well. I think that @nwin is no longer active on Github, we had planned to fork `lzw` and made a new crate for that reason.

**Comment by bvssvni** [comment]
Moved.

**Comment by bvssvni** [comment]
I've added `github:image-rs:publish` as owners on crates.io and remove `github:pistondevelopers:publish`.

**Comment by bvssvni** [comment]
@HeroicKatora @fintelia Do you have access to adding yourself as owners on crates.io? It might be nice to have a backup if something goes wrong when I remove myself. Or, I can just add you as owners.

**Comment by HeroicKatora** [comment]
> If a team name is given to --add, that team becomes a “team” owner, with restricted right to the crate. While they have permission to publish or yank versions of the crate, they do not have the ability to add or remove owners.

It doesn't seem possible to manage owners via a team access alone. So please add us individually as well.

**Comment by bvssvni** [comment]
@HeroicKatora @fintelia I sent you an invite to owner on crates.io. Feel free to remove me as owner.

**Comment by fintelia** [comment]
I accepted your invite

**Comment by HeroicKatora** [comment]
Yes, thank you!
